### ISSUE TITLE
Connecting reading client to writing server of Windows named pipe fails in 1.2.0

### ISSUE THREAD

**Issue by matthias-stemmler** [kotauskas/interprocess#23]
First of all, thanks for this great library!

**Describe the bug**
When trying to create a Windows named pipe using a `PipeListener<ByteWriterPipeStream>` and connecting to it using `ByteReaderPipeStream::connect`, connecting fails with the message "Access is denied".

Additional observations:
- It fails with version `1.2.0`, but works with version `1.1.1`.
- It only fails when the server is a writer and the client is a reader. If you swap `ByteWriterPipeStream` and `ByteReaderPipeStream` in the example below, it works.
- By using Git dependencies, I can see that this behavior starts occurring after commit https://github.com/kotauskas/interprocess/commit/909bddd17dbf25182987ae9aa25e5220617b44d1

**To Reproduce**
Run this test with a dependency on `interprocess = "=1.2.0"`:
```
use interprocess::os::windows::named_pipe::{
    ByteReaderPipeStream, ByteWriterPipeStream, PipeListener, PipeListenerOptions,
};
use std::ffi::OsStr;
use std::thread;

#[test]
fn test() {
    let listener: PipeListener<ByteWriterPipeStream> = PipeListenerOptions::new()
        .name(OsStr::new("test-pipe"))
        .create()
        .unwrap();

    let handle = thread::spawn(|| {
        ByteReaderPipeStream::connect("test-pipe").unwrap();
    });

    listener.accept().unwrap();

    handle.join().unwrap();
}
```

The test fails with this message:
```
thread 'test' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 5, kind: PermissionDenied, message: "Access is denied." }', tests\test.rs:18:23
```

**Expected behavior**
The test should succeed.

**Comment by kotauskas** [comment]
Just released 1.2.1 which should fix this issue.
