### ISSUE TITLE
Tokio: all read-methods except `read_line` never seem to resolve

### ISSUE THREAD

**Issue by on3iro** [kotauskas/interprocess#25]
**Describe the bug**
I am not sure if this is actually a bug or a user error on my side, but I can't seem to make interprocess work with tokio `rmp_serde`, because I somehow can't use any other reading operation other than `read_line()`.
Here is what I would like to achieve:
* I have a server listening for local socket connections
* whenever it receives a connection it starts a loop inside the connection which handles `read/write` continously
* Each client also loops inside their respective connection and reads/writes
* All writes use custom message enums (called `ClientToServerMsg` and `ServerToClientMsg`) which are encoded/decoded with `rmp_serde`.

Now I tried to follow the `interprocess` examples and at first used `read_line()` to read messages into a buffer.
When I use actual byte strings that works fine. However this does not work with messages which are encoded with rmp_serde (I assume because these messages might span multiple lines).
Therefore I tried to use a different read operation. However non of the other operations (`read`, `read_exaxt`, `read_to_end` etc.) seem to ever resolve. I `await` them, but the code afterwards is never being reached.

**To Reproduce**
* Follow the tokio example
* Write a vector of bytes with `writer.write_all` (instead of  the byte string from the example)
* Try to await any read operation other than `read_line`

**Expected behavior**
I would expect to resolve the other read operations returning a vector of bytes, similarly to the byte string returned by `read_line` and to reach code after the `read_xxx().await`.

**Code Examples**

**Client connection handler**
```rust
async fn handle_connection(
    connection: LocalSocketStream,
    terminal_out_tx: UnboundedSender<TerminalEvent>,
    mut terminal_in_rx: UnboundedReceiver<ClientInputAction>,
) -> anyhow::Result<()> {
    // This consumes our connection and splits it into two halves,
    // so that we could concurrently act on both.
    let (reader, mut writer) = connection.into_split();
    let mut reader = BufReader::new(reader);

    loop {
        // Allocate a sizeable buffer for reading.
        // This size should be enough and should be easy to find for the allocator.
        let mut buffer = vec![0; 1024];

        select! {
           // ... handle read task
           // ...,
           // Handle IPC write whenever we receive some terminal input
            value = terminal_in_rx.recv() => {
                if let Some(event) = value {
                    match event {
                        ClientInputAction::Quit => {
                            let msg = ClientToServerMsg::Quit;
                            let msg = rmp_serde::encode::to_vec::<ClientToServerMsg>(&msg).context("Could not encode ClientToServerMsg::Quit")?;

                            // Command server to shutdown (and send quit msg from server to other
                            // attached clients including this one)
                            writer.write_all(&msg).await.context("Could not write ClientToServerMsg to stream")?;
                        },
                        ClientInputAction::Detach => {
                            // Shutdown current client, but keep server running
                            terminal_out_tx.send(TerminalEvent::Quit).context("Could not send to terminal out")?;
                        },
                        ClientInputAction::None => continue,
                        ClientInputAction::PlayPause => {
                            let msg = ClientToServerMsg::PlayPause;
                            let msg = rmp_serde::encode::to_vec::<ClientToServerMsg>(&msg).context("Could not encode ClientToServerMsg::PlayPause")?;


                            // writer.write_all(&msg).await.context("Could not write ClientToServerMsg to stream")?;
                            let msg = b"Hello from client!\n";
                            writer.write_all(msg).await?;
                        },
                        ClientInputAction::Skip => {
                            let msg = ClientToServerMsg::Skip;
                            let msg = rmp_serde::encode::to_vec::<ClientToServerMsg>(&msg).context("Could not encode ClientToServerMsg::Skip")?;

                            writer.write_all(&msg).await.context("Could not write ClientToServerMsg to stream")?;
                        },
                    }
                }
            }
        };

        yield_now().await;
    }
}
```

**Server code which receives messages (simplified)**
```rust
// Describe the things we do when we've got a connection ready.
async fn handle_conn(
    conn: LocalSocketStream,
    timer_input_sender: Sender<TimerInputAction>,
    mut timer_output_receiver: BroadcastReceiver<TimerOutputAction>,
) -> anyhow::Result<()> {
    // Split the connection into two halves to process
    // received and sent data concurrently.
    let (reader, mut writer) = conn.into_split();
    let mut reader = BufReader::new(reader);


    loop {
        // Allocate a sizeable buffer for reading.
        // This size should be enough and should be easy to find for the allocator.
        let mut buffer = vec![0; 1024];

        println!("Server tries to receive message");

        reader.read_to_end(&mut buffer).await?;

       // BUG? //
       // This point is never being reached - the future above seems to never resolve     

        let msg = rmp_serde::from_slice::<ClientToServerMsg>(&buffer)
            .context("Could not decode ClientToServerMsg")?;

        println!("Server received: {:?}", msg);
    }
}
```

Any help is appreciated - thanks in advance :)

**Comment by kotauskas** [comment]
While I'm not quite sure yet why you'd have a problem with `.read_exact()`, I can tell you right out of the gate that `.read_to_end()` cannot possibly be used correctly on local sockets, as they do not have a shutdown operation. In other words, a local socket can only reach EOF when one of the sides of the connection drops their stream, and `.read_to_end()` in a loop is certainly not going to work in any situation.

The reason for this is quite simple: Windows named pipes do not have a notion of EOF at all, and instead convert "broken pipe" errors to an `Ok(0)` return value on reads, indicating an end-of-file condition. Because inducing a "broken pipe" error on the other side requires closing the connection, `.shutdown()` is impossible to implement as a method that shuts down only reads or only writes, and local sockets therefore cannot have it either.

I haven't investigated your specific code yet as of right now, but one thing I can point you towards is this pattern that I'm planning to implement as a first-class feature, "packet stream emulation", sometime soon:
- Upon encoding, take note of the encoded message length and cast it to a fixed-size integer (`u32` should work, you're not sending 4 GB messages, are you?)
- Convert the length to a byte string using `.to_le_bytes()` (or use big-endian encoding instead, no big difference).
- Send the length and then the message into the stream with `.write_all()`.
- On the other side of the connection:
   ```rs
   let mut buf = [0_u8; 4]; // Change if message length uses different integer size
   conn.read_exact(&mut buf)?;
   let len = u32::from_le_bytes(buf);
   ```
   This will decode the previously sent length back into an integer.
- Use `.read_exact()` again, but with a buffer that is exactly `len` bytes long (subslice to `&mut buf[0..len]` if the allocated buffer is bigger).
- Deserialize from the same slice as given to previous `.read_exact()`.

If you'd like to gracefully handle an abrupt end of transmission, watch out for the `io::ErrorKind::UnexpectedEof` kind of error from `.read_exact()`. That indicates that the buffer slice you passed to it hasn't been filled entirely.

This effectively implements a local socket stream with message semantics, rather than plain stream semantics. Never at any point do you perform an unbounded read in this situation – EOF (or, as commonly is, lack thereof) has no bearing on the program other than its error cases.

**Comment by on3iro** [comment]
Thanks a ton for the detailed answer. The pattern you describe sounds really promising. I'll try it out asap and will let you know if I was able to fix my issue.

**Comment by on3iro** [comment]
@kotauskas Hey, I tried implementing your suggested solution, but I am still having some trouble (the actual message buffer seems to be empty - the msg containing the length seems ok however). Could you please take a look at my IPC-implementation below and tell me if the implementation of your suggestion looks correct? That would be super helpful. Thanks again!

```rust
impl InterProcessCommunication {
    pub async fn send_ipc_message<M>(msg: M, writer: &mut OwnedWriteHalf) -> anyhow::Result<()>
    where
        M: Serialize + for<'a> Deserialize<'a> + Debug,
    {
        let encoded_msg =
            rmp_serde::encode::to_vec::<M>(&msg).context(format!("Could not encode {:?}", msg))?;
        let msg_length =
            u32::try_from(encoded_msg.len()).context("Could not cast msg length to u32")?;
        let msg_length = msg_length.to_le_bytes();

        // Write msg with length to the stream (see [Self::recv_ipc_message] for why this is needed)
        writer
            .write_all(&msg_length)
            .await
            .context("Could not write message length to stream")?;

        // Write actual msg to the stream
        writer
            .write_all(&msg_length)
            .await
            .context(format!("Could not write {:?} to stream", msg))?;

        Ok(())
    }

    pub async fn recv_ipc_message<M>(reader: &mut BufReader<OwnedReadHalf>) -> anyhow::Result<M>
    where
        M: Serialize + for<'a> Deserialize<'a> + Debug,
    {
        // Read message length, so that we can make an exact read of the actual message afterwards
        let mut buffer = [0_u8; 4];

        reader
            .read_exact(&mut buffer)
            .await
            .context("Could not read msg length")?;
        let msg_length = u32::from_le_bytes(buffer);

        let mut buffer = Vec::with_capacity(
            usize::try_from(msg_length).context("Could not convert message length to usize")?,
        );

        // Read message of previously determined length, decode and return it
        reader
            .read_exact(&mut buffer)
            .await
            .context("Could not read message")?;

        rmp_serde::from_slice::<M>(&buffer).context("Could not decode msg")
    }
}
```

**Comment by on3iro** [comment]
Nevermind, I had an error inside my `send_ipc_message()` method 😬  - I wrote the length twice to  the stream instead of writing the message itself inside my second `write_all()` call. At first glance this seems to have resolved the issue, though I need to check it with my full code, yet. But it looks promising. I'll let you know if everything works.

Maybe we could add a small example with your proposed architecture and rmp_serde to the repositories examples? I could try to build one and make a PR :)

**Comment by on3iro** [comment]
Your solution works, thanks again 🎉 .
Again: If you want me to build a small example and make a PR just let me know.
