### ISSUE TITLE
Compilation errors on Mac OS Catalina

### ISSUE THREAD

**Issue by tikue** [kotauskas/interprocess#3]
**Describe the bug**
I am unable to build interprocess on Mac OS.

**To Reproduce**
Mac OS Catalina
Version 10.15.7

1. `git clone https://github.com/kotauskas/interprocess`
2. `cd interprocess`
3. `cargo build`

**Screenshots**
 [gist](https://gist.github.com/tikue/cf2f7af5aca3364a69bf1fae8a736c1e)

**Comment by kotauskas** [comment]
Fixed in 1.0.1, should not break again with the new CI matrix which also tests on macOS and not just Windows and Linux.
