### ISSUE TITLE
Documentation fails to build in crates that depend on interprocess without the tokio feature

### ISSUE THREAD

**Issue by ealmloff** [kotauskas/interprocess#32]
**Describe the bug**
When you run `cargo doc` on a crate that depends on interprocess without the tokio feature it fails because the tokio feature is not enabled.

**To Reproduce**
1) Create an empty crate with this in the cargo.toml:
```toml
[dependencies]
interprocess = { version = "1.2.1" }
```
2) Run `cargo doc`

**Expected behavior**
The docs successfully build

**Screenshots**
![image](https://user-images.githubusercontent.com/66571940/214946958-4ff038ab-412a-4ecb-a170-495aa4adbd6e.png)

**Additional context**
This was run on Windows 11.

**Comment by Demonthos** [comment]
This seems to be fixed on master. It just hasn't been released yet

**Comment by kotauskas** [comment]
2.0.0 has been released, closing.
