### ISSUE TITLE
Defining local socket names as const

### ISSUE THREAD

**Issue by RAVN-Mateus** [kotauskas/interprocess#36]
**Is your feature request related to a problem? Please describe.**
Looking at this snippet of your local socket client example:
```
// Pick a name. There isn't a helper function for this, mostly because it's largely unnecessary:
// in Rust, `match` is your concise, readable and expressive decision making construct.
let name = {
    // This scoping trick allows us to nicely contain the import inside the `match`, so that if
    // any imports of variants named `Both` happen down the line, they won't collide with the
    // enum we're working with here. Maybe someone should make a macro for this.
    use NameTypeSupport::*;
    match NameTypeSupport::query() {
        OnlyPaths => "/tmp/example.sock",
        OnlyNamespaced | Both => "@example.sock",
    }
};
```
I thought: "why can't i make this const? Both `query()` and `name_type_support_query()` are basically already `const`, they only lack the keyword before them."

**Describe the solution you'd like**
Make both those functions `const`. Maybe even introduce a `const fn` taking `name: &'static str` and returning either `@example.sock` or `/tmp/example.sock` based on possibility.

**Describe alternatives you've considered**
Exposing the `interprocess::os::???::local_socket::NAME_TYPE_ALWAYS_SUPPORTED` constant

**Comment by kotauskas** [comment]
The non-`const` functions were originally intended for future-proofing for Unix domain sockets on Windows, which are only supported on Windows 10 after a certain update, so support for path-type names isn't guaranteed at compile time (but can be queried for and taken advantage of at runtime, by checking the OS version).

>**Describe alternatives you've considered**
>Exposing the `interprocess::os::???::local_socket::NAME_TYPE_ALWAYS_SUPPORTED` constant

`NameTypeSupport` [has it] as an alternative to `query()` – examples deliberately don't use it so as to teach the reader the more flexible approach of deciding at runtime.

[0]: https://docs.rs/interprocess/1.2.1/interprocess/local_socket/enum.NameTypeSupport.html#associatedconstant.ALWAYS_AVAILABLE
