### ISSUE TITLE
Fails to compile on Pop!_OS 22.04 LTS

### ISSUE THREAD

**Issue by dxps** [kotauskas/interprocess#37]
**Describe the bug**

It fails to compile on Pop!_OS 22.04 LTS (Linux distro).
Using Rust ver. 1.69.0.

**Additional context**

```
Error: 🚫 Serving project failed: error: Your target operating system is not supported by interprocess – check if yours is in the list of supported systems, and if not, please open an issue on the GitHub repository if you think that it should be included
  --> /home/dxps/.cargo/registry/src/github.com-1ecc6299db9ec823/interprocess-1.2.1/src/lib.rs:82:1
   |
82 | compile_error!("Your target operating system is not supported by interprocess – check if yours is in the list of supported systems, and if not, please open an issue on the GitHub repository if you think that it should be included...
```

Any hints, please?

Meanwhile, I'll see if I can find the solution.

Thanks!

**Comment by kotauskas** [comment]
The only reason why this might be happening is that your target isn't Windows or Unix for one reason or another. WebAssembly comes to mind as an unsupported target that cannot have any support for the IPC primitives that the crate implements, and looking at what Dioxus does, I reckon it's quite likely that code which isn't supposed to be ran as WASM is erroneously being compiled to it.

**Comment by dxps** [comment]
@kotauskas Thanks for the feedback! :pray: 
Yes, I believe that's the rationale: Dioxus' Desktop (non WASM) target would benefit from this.
