### ISSUE TITLE
`tokio_named_pipe` fails frequently

### ISSUE THREAD

**Issue by ncihnegn** [kotauskas/interprocess#47]
```
error: test failed, to rerun pass `--test tokio_named_pipe`

Caused by:
  process didn't exit successfully: `\interprocess\target\debug\deps\tokio_named_pipe.exe` (exit code: 0xc0000374, STATUS_HEAP_CORRUPTION)
```

```
Caused by:
  process didn't exit successfully: `\interprocess\target\debug\deps\tokio_named_pipe.exe` (exit code: 0xc0000005, STATUS_ACCESS_VIOLATION)
```

`cargo test --features="tokio"` on Windows 11 22H2 (OS Build 22621.2506).

Occasionally it passes.

**Comment by RivenSkaye** [comment]
Could that have been an issue on nightly? Running it several times over goes flawlessly on my end, save for an unused import warning.
w10 Pro 22H2 on my end, if that could be making a difference

**Comment by kotauskas** [comment]
I'm fairly sure that was a Tokio bug. Since tests now reliably pass on my machine and in CI, I'm gonna close this one.
