### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by rklaehn** [kotauskas/interprocess#48]
We want to use interprocess in https://github.com/n0-computer/quic-rpc for use in https://github.com/n0-computer/iroh .

We are seeing several test failures with the currently published version, specifically on windows. They **all** seem to be fixed with the version on main. However, we can't release with a git dependency.

Could you release the current state? Maybe with a milestone release so you don't have to fix the API for v2?

**Comment by onbjerg** [comment]
Second this, any chance we can get a release soon?

**Comment by kotauskas** [comment]
[Right about now](<https://github.com/kotauskas/interprocess/releases/tag/2.0.0>), yes.
